### ISSUE TITLE
Error: Image with src "[object Object]" is missing "loader" prop

### ISSUE THREAD

**Issue by eerison** [Niels-IO/next-image-export-optimizer#121]
Could someone help me with this error?

exception

```
 error - node_modules/next/dist/client/image.js (345:18) @ eval
lili-im-deutschland-node-1  | error - Error: Image with src "[object Object]" is missing "loader" prop.
lili-im-deutschland-node-1  | Read more: https://nextjs.org/docs/messages/next-image-missing-loader
lili-im-deutschland-node-1  |     at eval (webpack-internal:///./node_modules/next/dist/client/image.js:343:19)
lili-im-deutschland-node-1  |     at renderWithHooks (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
lili-im-deutschland-node-1  |     at renderForwardRef (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5842:18)
lili-im-deutschland-node-1  |     at renderElement (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6005:11)
lili-im-deutschland-node-1  |     at renderNodeDestructiveImpl (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
lili-im-deutschland-node-1  |     at renderNodeDestructive (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
lili-im-deutschland-node-1  |     at renderNode (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
lili-im-deutschland-node-1  |     at renderHostElement (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
lili-im-deutschland-node-1  |     at renderElement (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
lili-im-deutschland-node-1  |     at renderNodeDestructiveImpl (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
lili-im-deutschland-node-1  |     at renderNodeDestructive (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
lili-im-deutschland-node-1  |     at renderForwardRef (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5859:5)
lili-im-deutschland-node-1  |     at renderElement (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6005:11)
lili-im-deutschland-node-1  |     at renderNodeDestructiveImpl (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
lili-im-deutschland-node-1  |     at renderNodeDestructive (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
lili-im-deutschland-node-1  |     at renderIndeterminateComponent (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
lili-im-deutschland-node-1  |     at renderElement (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
lili-im-deutschland-node-1  |     at renderNodeDestructiveImpl (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
lili-im-deutschland-node-1  |     at renderNodeDestructive (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
lili-im-deutschland-node-1  |     at renderNode (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
lili-im-deutschland-node-1  |     at renderHostElement (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
lili-im-deutschland-node-1  |     at renderElement (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
lili-im-deutschland-node-1  |     at renderNodeDestructiveImpl (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
lili-im-deutschland-node-1  |     at renderNodeDestructive (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
lili-im-deutschland-node-1  |     at renderNode (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
lili-im-deutschland-node-1  |     at renderHostElement (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
lili-im-deutschland-node-1  |     at renderElement (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
lili-im-deutschland-node-1  |     at renderNodeDestructiveImpl (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
lili-im-deutschland-node-1  |     at renderNodeDestructive (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
lili-im-deutschland-node-1  |     at renderIndeterminateComponent (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
lili-im-deutschland-node-1  |     at renderElement (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
lili-im-deutschland-node-1  |     at renderNodeDestructiveImpl (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
lili-im-deutschland-node-1  |     at renderNodeDestructive (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
lili-im-deutschland-node-1  |     at renderNode (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
lili-im-deutschland-node-1  |     at renderChildrenArray (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
lili-im-deutschland-node-1  |     at renderNodeDestructiveImpl (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
lili-im-deutschland-node-1  |     at renderNodeDestructive (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
lili-im-deutschland-node-1  |     at renderNode (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
lili-im-deutschland-node-1  |     at renderHostElement (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
lili-im-deutschland-node-1  |     at renderElement (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
lili-im-deutschland-node-1  |     at renderNodeDestructiveImpl (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
lili-im-deutschland-node-1  |     at renderNodeDestructive (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
lili-im-deutschland-node-1  |     at renderIndeterminateComponent (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
lili-im-deutschland-node-1  |     at renderElement (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
lili-im-deutschland-node-1  |     at renderNodeDestructiveImpl (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
lili-im-deutschland-node-1  |     at renderNodeDestructive (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
lili-im-deutschland-node-1  |     at renderIndeterminateComponent (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
lili-im-deutschland-node-1  |     at renderElement (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
lili-im-deutschland-node-1  |     at renderNodeDestructiveImpl (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
lili-im-deutschland-node-1  |     at renderNodeDestructive (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14) {
lili-im-deutschland-node-1  |   page: '/'
lili-im-deutschland-node-1  | }

```

config

```
const nextConfig = {
    images: {
        loader: "custom",
        formats: ['image/webp'],
        imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
        deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
    },
    transpilePackages: ["next-image-export-optimizer"],
    env: {
        nextImageExportOptimizer_imageFolderPath: "public/assets",
        nextImageExportOptimizer_exportFolderPath: "out",
        nextImageExportOptimizer_quality: 75,
        nextImageExportOptimizer_storePicturesInWEBP: true,
        nextImageExportOptimizer_exportFolderName: "nextImageExportOptimizer",
        
        // If you do not want to use blurry placeholder images, then you can set
        // nextImageExportOptimizer_generateAndUseBlurImages to false and pass
        // `placeholder="empty"` to all <ExportedImage> components.
        //
        // If nextImageExportOptimizer_generateAndUseBlurImages is false and you
        // forget to set `placeholder="empty"`, you'll see 404 errors for the missing
        // placeholder images in the console.
        nextImageExportOptimizer_generateAndUseBlurImages: true,
    },
}

module.exports = nextConfig
```

code

```
    return <ExportedImage
        // src={image.path}
        src="/assets/blog/test/cover.jpg"
        // alt={image.alt}
        alt="abc"
        width={width}
        height={height}
    />;
```

**Comment by eerison** [comment]
It was my mistake, I forget to change one next/image for ExportedImage

Thank you guys :)

**Comment by ImtiazNayeemShawon** [comment]
Share the updated code please

**Comment by terrinens** [comment]
I leave it to someone looking for bugs like me.

This error occurs if you have used the components of importing images from "Next/Image" anywhere in your project.

Therefore, for normal operation, all <Image> components must be changed to <Export Image> to operate normally.
