### ISSUE TITLE
CLI tool does not even start on Mac (1.14.1)

### ISSUE THREAD

**Issue by mcbain** [Niels-IO/next-image-export-optimizer#225]
```
MacBook-Pro:react-blog jenszastrow$ yarn next-image-export-optimizer
yarn run v1.22.19
$ /Users/jenszastrow/jzs/lead-engine/templates/react-blog/node_modules/.bin/next-image-export-optimizer
/Users/jenszastrow/jzs/lead-engine/templates/react-blog/node_modules/cli-progress/lib/formatter.js:1
const _stringWidth = require('string-width');
                     ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/jenszastrow/jzs/lead-engine/templates/react-blog/node_modules/string-width/index.js from /Users/jenszastrow/jzs/lead-engine/templates/react-blog/node_modules/cli-progress/lib/formatter.js not supported.
Instead change the require of index.js in /Users/jenszastrow/jzs/lead-engine/templates/react-blog/node_modules/cli-progress/lib/formatter.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/jenszastrow/jzs/lead-engine/templates/react-blog/node_modules/cli-progress/lib/formatter.js:1:22)
    at Object.<anonymous> (/Users/jenszastrow/jzs/lead-engine/templates/react-blog/node_modules/cli-progress/lib/generic-bar.js:3:20)
    at Object.<anonymous> (/Users/jenszastrow/jzs/lead-engine/templates/react-blog/node_modules/cli-progress/lib/single-bar.js:1:21)
    at Object.<anonymous> (/Users/jenszastrow/jzs/lead-engine/templates/react-blog/node_modules/cli-progress/cli-progress.js:1:20)
    at Object.<anonymous> (/Users/jenszastrow/jzs/lead-engine/templates/react-blog/node_modules/next-image-export-optimizer/dist/utils/defineProgressBar.js:3:21)
    at Object.<anonymous> (/Users/jenszastrow/jzs/lead-engine/templates/react-blog/node_modules/next-image-export-optimizer/dist/optimizeImages.js:4:27) {
  code: 'ERR_REQUIRE_ESM'
}
Node.js v18.18.2
```

**Comment by Niels-IO** [comment]
Hi @mcbain, 
it works on my Mac but I found this related open issue:
https://github.com/npkgz/cli-progress/issues/155
Not sure when this will be fixed and how I can address this in this library.

**Comment by jack828** [comment]
I worked around this as part of my applications build process by using `tsx`

For example:

```
$ tsx ./node_modules/.bin/next-image-export-optimizer
```
