### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by reinveenstra** [Niels-IO/next-image-export-optimizer#7]
Thanks for writing this plugin!

When using export build I get the following error.

```
Export successful. Files written to /project/websites//out
/project/websites//node_modules/next-image-export-optimizer/src/optimizeImages.js:78
    if (nextjsConfig.images?.nextImageExportOptimizer?.imageFolderPath) {
                            ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by Niels-IO** [comment]
Hi @reinveenstra ,

I am not 100% I understand where the error is coming from. I just published version 0.7.2 which includes more safeguards if the nextjsConfig variable is not an object or is null. Could you try it, please?

**Comment by reinveenstra** [comment]
Hey,

I just tried it out, it keeps throwing an error :/

**Comment by reinveenstra** [comment]
Update 0.8 fixed it. Thanks for all the effort!
