### ISSUE TITLE
Jest failing on ExportedImage.d.ts

### ISSUE THREAD

**Issue by stefangoor** [Niels-IO/next-image-export-optimizer#75]
Hi There,

Since updating to v1.0 my Jest tests are failing with the following:

```
Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /development/myproject/node_modules/next-image-export-optimizer/dist/ExportedImage.d.ts:2
    import { ImageProps, StaticImageData } from "next/image";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import { Grid, Typography } from '@mui/material';
    > 2 | import ExportedImage from 'next-image-export-optimizer';
        | ^
      3 | import { useContext } from 'react';
      4 |
      5 | import BrandContext from '../../contexts/BrandContext';

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1796:14)
      at Object.<anonymous> (components/USP/USP.tsx:2:1)
```

I have tried adding a the transformIgnorePatterns to the jest.config.js to ignore the ExportedImage.d.ts but I still keep getting the error on all code importing ExportedImage.

I'm not sure how to resolve the issue so any advice would be great.

Many thanks,
Stefan

**Comment by Niels-IO** [comment]
Hi @stefangoor,

Thanks for letting me know. To be sure, have you tried to use the _transformIgnorePatterns_ as suggested in this answer?
https://stackoverflow.com/a/70883655/17515424

**Comment by stefangoor** [comment]
Hi @Niels-IO 

Thanks for replying.

When I put in the exclude as:

```
"transformIgnorePatterns": [
    "/node_modules/(?!(next-image-export-optimizer)/)"
 ],
```

(I have the forward slash as I'm using an nx monorepo)

But when I exclude the package entirely, I get errors about ExportedImage not being found:

```
Error: Uncaught [Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

      Check the render method of `Banner`.]
```

Does the class need to be mocked for tests?

I did try to just exclude the .d.ts file but it wasn't making any difference.

Many thanks,
Stefan

**Comment by Niels-IO** [comment]
Hi @stefangoor, 

I am a bit clueless at the moment. Is it possible to create a codesandbox or a branch with a jest error in the example directory of this package?

It would help me dig into it.

**Comment by stefangoor** [comment]
Hi @Niels-IO 

Thanks for replying, I will arrange that, but it will be next week before I can look into that.  I hope that's ok.

Thanks,
Stefan

**Comment by Niels-IO** [comment]
Hi @stefangoor,

Could you please try to change the import of next-image-export-optimizer to a require and see if the error persists?

const ExportedImage = require('next-image-export-optimizer');
